### ISSUE TITLE
Set up new CNAME record for Ember.js documentary landing page

### ISSUE THREAD

**Issue by Kinghams22** [honeypotio/website#25]
Hey guys,

We'd like to host the video of the ember documentary on an (unbounce) landing page, which means we need to use a subdomain. FYI, we previously did this to create the doc. subdomain for the elixir documentary.

Anyway, we want to host all documentaries on the same subdomain but would prefer not to use doc.

From now on, we would like to host documentaries on videos.honeypot.io, so we would need to set up a new CNAME record in our DNS settings for "videos" and have it point to unbouncepages.com

Once we have published the ember documentary on videos.honeypot.io, I will then change the subdomain of the elixir documentary from doc. to videos. and set up redirects.

**To be clear, this is what we need to do, according to unbounce:**

- [ ] Log in to your domain provider for honeypot.io and navigate to anything related to DNS Settings or something close to it.
- [ ] From there, add a CNAME record for **videos** and have it point to **unbouncepages.com**

Cheers!

**Comment by kdamball** [comment]
@munya44 for next scoping

**Comment by Kinghams22** [comment]
@emmalou Hey here's the ticket for the CNAME record needed to publish the Ember landing page on Monday

**Comment by Ryman** [comment]
@Kinghams22 @emmalou  https://videos.honeypot.io now redirects but I can't test if it's sufficient as you haven't told us the filepath with which to test it works 🙈

**Comment by Ryman** [comment]
Done! confirmed by @Kinghams22
