### ISSUE TITLE
HiveConf 2018 website down

### ISSUE THREAD

**Issue by Kinghams22** [honeypotio/website#36]
Hey guys, https://hive.honeypot.io/hive-conference-2018/ is down and giving us a 404.

There are several links on the website leading to this page, meaning broken links + we've sent this link to many potential attendees of the 2019 edition so they can see what it's all about. Would be great if we can get this page live again asap.

**Comment by kdamball** [comment]
Fixed with redirect on new hive subdomain. We had no control of the netlify deploy on 2018 hive.
