### ISSUE TITLE
Terms of service numbering mixed up

### ISSUE THREAD

**Issue by computhomas** [honeypotio/website#44]
The numeration isn't as intended on https://www.honeypot.io/en/terms_of_service

Example "Talent ToS, Number 9"

9.1.1 to 9.1.5 should be indented under 9.1 but are instead shown as 9.2 to 9.6

In Github it looks like this:
![image](https://user-images.githubusercontent.com/4354574/58036220-dd1cb600-7b2a-11e9-9c3e-e53424a65354.png)

On the Website it looks like this:
![image](https://user-images.githubusercontent.com/4354574/58036242-ead23b80-7b2a-11e9-8a7a-0e1d9a06e689.png)

And actually it should be:
![image](https://user-images.githubusercontent.com/4354574/58036329-1ead6100-7b2b-11e9-9b45-da7b774721de.png)

@kdamball

**Comment by lean8086** [comment]
QA:

- It happens in 4.5.x and 9.1.x on Talents section
- It happens in 2.5.x, 8.1.x and 11.5.x on Employers section

**Comment by kdamball** [comment]
QA Links:
http://staging.honeypot.co/pr-52/en/terms_of_service/

**Comment by kdamball** [comment]
From @computhomas 

> thomas [4:26 PM]
Indention looks fine. More space before the section headers would look beeter though

&nbsp;

![image](https://user-images.githubusercontent.com/3318312/58890230-84cce300-86ea-11e9-8a57-2ead6f0aad2b.png)

**Comment by lean8086** [comment]
Done!
