### ISSUE TITLE
CNAME record (fly.honeypot.io) for Easyjet campaign

### ISSUE THREAD

**Issue by Kinghams22** [honeypotio/website#47]
Hey Kevin mate, could you please help me add another one of those CNAME records? :) Should be the last one! Would need this before the end of the week as it'll be going live on Satuday! Sorry for the extremely short notice but Easyjet gave us a really tight deadline.

**More info:**
We're publishing another subdomain on Unbounce and would therefore need you folks to help adding a new CNAME record please. We won't be adding more subdomains for fun, all documentaries will be hosted on videos.honeypot.io and all landing pages will be on hello.honeypot.io. This time we just want to make fly.honeypot.io specifically for the upcoming Easyjet campaign.

**To be clear, this is what we need to do, according to unbounce:**

- Log in to your domain provider for honeypot.io and navigate to anything related to DNS Settings or something close to it.
- Add a CNAME record for fly and paste the following so it points to: 82924288addc4f978eec154bdffab38b.unbouncepages.com 

Cheers!

**Comment by Ryman** [comment]
done

**Comment by Kinghams22** [comment]
Thanks mate!
