### ISSUE TITLE
Update of Hive link on Community page

### ISSUE THREAD

**Issue by korenroos** [honeypotio/website#60]
From https://www.honeypot.io/en/community/ page the link for Hive Conference should be changed (as we have a new page)

- [ ] To change the link for Hive Conference to https://hive.honeypot.io/
- [ ] To change Hive Conference to **HiveConf**

**Comment by Ryman** [comment]
@Kinghams22 can we please make `hive.honeypot.io` show the current page so we can just link to that and not change every year?

**Comment by korenroos** [comment]
@Ryman, just checked with Bugra -- https://hive.honeypot.io/ works just fine actually

**Comment by Kinghams22** [comment]
@moekify can't seem to find the right repo. Any chance you can help me change the HiveConf link on the community page from https://hive.honeypot.io/hive-conference-2018/ to https://hive.honeypot.io ? Would be greatly appreciated :)

**Comment by Kinghams22** [comment]
@moekify + We'd need to change it on all 3 language versions of the website, not just the /en version
